/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: (string | { url: string; revision: string })[];
};

import { clientsClaim } from "workbox-core";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate, CacheFirst } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

// Cache versioning - change this to force a fresh start if needed
const CACHE_VERSION = "v2.1.0";
const CACHE_NAME = `aspire-cache-${CACHE_VERSION}`;

clientsClaim();

// Handle SKIP_WAITING message
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Precache all assets generated by build
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old Workbox caches
cleanupOutdatedCaches();

// Custom Cache Cleanup for our own versioned caches
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name.startsWith("aspire-cache-") && name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      );
    })
  );
  console.log(`[SW] Activated ${CACHE_VERSION}`);
});

// Cache Images
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "images",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache other assets
registerRoute(
  ({ request }) => 
    request.destination === "script" || 
    request.destination === "style",
  new StaleWhileRevalidate({
    cacheName: "static-resources",
  })
);
